/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class javasec_jnisec_CmdDemo */

#ifndef _Included_javasec_jnisec_CmdDemo
#define _Included_javasec_jnisec_CmdDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javasec_jnisec_CmdDemo
 * Method:    exec
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_javasec_jnisec_CmdDemo_exec
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
